# Generated by Django 2.0.3 on 2018-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='intermediaryRemark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='intermediarySourcesCompleted',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='projectState',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='projectType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='writerRemark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
